"""Compatibility bridge from the existing Decky UI/profile schema to official lsfg-vk v2+ upstream.

This module is only activated in the generated v3 package. It keeps the proven
Decky UI while writing a second, upstream-native TOML file watched by the new
engine. v2 remains untouched on disk.

The v3 launcher intentionally preserves the useful script-side Odin/SteamOS
controls from v2 (DXVK base FPS cap, WOW64, SteamDeck mode, MangoHud/vkBasalt,
Gamescope WSI and Zink) because these are launcher/environment features and do
not depend on the lsfg-vk core version.
"""

from __future__ import annotations

import os
from pathlib import Path

from .config_schema_generated import get_script_generation_logic


def _q(value: object) -> str:
    s = str(value).replace('\\', '\\\\').replace('"', '\\"')
    return f'"{s}"'


def _shell_q(value: object) -> str:
    return "'" + str(value).replace("'", "'\\''") + "'"


def apply_v3_bridge(ConfigurationService, ConfigurationManager, DEFAULT_PROFILE_NAME):
    def upstream_path(self):
        return self.user_home / ".config/decky-lsfg-vk3-arm64/upstream.toml"

    def write_upstream(self, profile_data):
        current = profile_data.get("current_profile") or DEFAULT_PROFILE_NAME
        profiles = profile_data.get("profiles") or {}
        cfg = dict(profiles.get(current) or ConfigurationManager.get_defaults())
        global_cfg = dict(profile_data.get("global_config") or {})

        multiplier = int(cfg.get("multiplier", 2) or 2)
        multiplier = max(1, min(multiplier, 4))
        flow = float(cfg.get("flow_scale", 1.0) or 1.0)
        flow = max(0.25, min(flow, 1.0))
        performance = bool(cfg.get("performance_mode", False))

        # The old UI exposes no_fp16 while current official upstream exposes
        # allow_fp16. Keep the old control and invert it here.
        allow_fp16 = not bool(global_cfg.get("no_fp16", cfg.get("no_fp16", False)))
        dll = str(global_cfg.get("dll", cfg.get("dll", "")) or "")

        # New upstream reads lsfg-vk.dll. If the old UI points at Lossless.dll,
        # use a sibling lsfg-vk.dll when present; otherwise omit the override
        # so upstream can auto-detect the Steam installation.
        dll_line = None
        if dll:
            p = Path(dll).expanduser()
            if p.name.lower() == "lsfg-vk.dll" and p.is_file():
                dll_line = f"dll = {_q(p)}"
            else:
                sibling = p.parent / "lsfg-vk.dll"
                if sibling.is_file():
                    dll_line = f"dll = {_q(sibling)}"

        log_path = self.user_home / ".config/decky-lsfg-vk3-arm64/lsfg-vk.log"
        lines = [
            "version = 2",
            "",
            "# Generated by Decky LSFG-VK 3 ARM64",
            "[global]",
            f"allow_fp16 = {'true' if allow_fp16 else 'false'}",
            'log_level = "info"',
            f"log_file = {_q(log_path)}",
        ]
        if dll_line:
            lines.append(dll_line)
        lines += [
            "",
            "[[profile]]",
            f"name = {_q(current)}",
            f"multiplier = {multiplier}",
            f"flow_scale = {flow:.4f}".rstrip("0").rstrip("."),
            f"performance_mode = {'true' if performance else 'false'}",
            'pacing_mode = "vsync"',
            "override_present_mode = true",
            "",
        ]

        path = upstream_path(self)
        path.parent.mkdir(parents=True, exist_ok=True)
        tmp = path.with_name(".upstream.toml.tmp")
        tmp.write_text("\n".join(lines), encoding="utf-8")
        os.replace(tmp, path)
        return path

    def wrapper_for_profile(self, profile_data):
        current = profile_data.get("current_profile") or DEFAULT_PROFILE_NAME
        cfg = dict((profile_data.get("profiles") or {}).get(current) or ConfigurationManager.get_defaults())
        global_cfg = dict(profile_data.get("global_config") or {})
        merged_cfg = dict(cfg)
        merged_cfg.update(global_cfg)

        multiplier = int(cfg.get("multiplier", 2) or 2)
        config_path = write_upstream(self, profile_data)
        manifest_dir = self.user_home / ".local/share/decky-lsfg-vk3-arm64/layer"
        manifest = manifest_dir / "VkLayer_LSFGVK_frame_generation.json"

        # Preserve every v2 launcher-side control. This restores:
        # - Base FPS cap -> DXVK_FRAME_RATE
        # - PROTON_USE_WOW64
        # - SteamDeck=0
        # - MangoHud workaround
        # - vkBasalt disable/force-enable
        # - Gamescope WSI toggle (+ DXVK_HDR behavior from the existing UI)
        # - Zink environment
        env_lines = list(get_script_generation_logic()(merged_cfg))

        lines = [
            "#!/bin/bash",
            "# LSFG-VK 3 ARM64 launcher. Roll back by changing ONE digit: 3 -> 2.",
            f"export LSFGVK_CONFIG={_shell_q(config_path)}",
            f"export LSFGVK_PROFILE={_shell_q(current)}",
        ]
        lines.extend(env_lines)
        lines += [
            f"MANIFEST={_shell_q(manifest)}",
            f"MANIFEST_DIR={_shell_q(manifest_dir)}",
            "",
            "# True native 1X on launch: do not inject the Vulkan layer at all.",
            f"START_MULTIPLIER={max(1, min(multiplier, 4))}",
            "if [ \"$START_MULTIPLIER\" -le 1 ] && [ \"${LSFGVK_HOT_1X:-0}\" != \"1\" ]; then",
            "  export DISABLE_LSFGVK=1",
            "  unset VK_IMPLICIT_LAYER_PATH VK_ADD_IMPLICIT_LAYER_PATH",
            "  exec \"$@\"",
            "fi",
            "",
            "if [ ! -f \"$MANIFEST\" ]; then",
            "  echo \"LSFG-VK 3 ARM64: layer manifest missing: $MANIFEST\" >&2",
            "  exit 66",
            "fi",
            "unset DISABLE_LSFGVK",
            "unset VK_ADD_IMPLICIT_LAYER_PATH",
            "export VK_IMPLICIT_LAYER_PATH=\"$MANIFEST_DIR\"",
            f"export LSFG_PROCESS={_shell_q(current)}",
            "exec \"$@\"",
            "",
        ]
        return "\n".join(lines)

    def generate_profile(self, profile_data):
        return wrapper_for_profile(self, profile_data)

    def generate_single(self, config):
        profile_data = {
            "current_profile": DEFAULT_PROFILE_NAME,
            "profiles": {DEFAULT_PROFILE_NAME: dict(config)},
            "global_config": {
                "dll": config.get("dll", ""),
                "no_fp16": config.get("no_fp16", False),
            },
        }
        return wrapper_for_profile(self, profile_data)

    def update_script(self, profile_data):
        try:
            script = wrapper_for_profile(self, profile_data)
            self._write_file(self.lsfg_script_path, script, 0o755)
            current = profile_data.get("current_profile") or DEFAULT_PROFILE_NAME
            current_cfg = (profile_data.get("profiles") or {}).get(current, ConfigurationManager.get_defaults())
            return self._success_response(dict, "LSFG-VK 3 ARM64 launcher updated", config=current_cfg)
        except Exception as exc:
            return self._error_response(dict, str(exc), config=None)

    ConfigurationService._generate_script_content = generate_single
    ConfigurationService._generate_script_content_for_profile = generate_profile
    ConfigurationService.update_lsfg_script_from_profile_data = update_script
